apiVersion: v1
kind: ConfigMap
metadata:
  namespace: omotes
  annotations:
    use-subpath: "true"
  name: env-vars-cm
data:
  POSTGRES_ROOT_USER: "root"
  POSTGRES_DEV_PORT: "6432"
  POSTGRES_ORCHESTRATOR_USER_NAME: "omotes_orchestrator"

  RABBITMQ_PORT: "5672"
  RABBITMQ_ROOT_USER: "root"
  RABBITMQ_OMOTES_USER_NAME: "omotes"
  RABBITMQ_CELERY_USER_NAME: "celery"

  INFLUXDB_PORT: "8096"
  INFLUXDB_RPC_PORT: "8098"
  INFLUXDB_PORT_BIND: ":8096"
  INFLUXDB_RPC_PORT_BIND: ":8098"
  INFLUXDB_ADMIN_USER: "root"
  INFLUXDB_WRITE_USER: "write1"
  INFLUXDB_FRONTEND_ADMIN_USER: "front1"

  WORKFLOW_SETTINGS_FILE: "./config/workflow_config_nwn_9sept2024.json"

  LOG_LEVEL: "INFO"

---
apiVersion: v1
kind: Secret
metadata:
  namespace: omotes
  name: env-vars-secrets
type: Opaque
data:
  POSTGRES_ROOT_PASSWORD: "MTIzNA=="
  POSTGRES_ORCHESTRATOR_USER_PASSWORD: "c29tZXBhc3Mz"

  RABBITMQ_ROOT_PASSWORD: "NTY3OA=="
  RABBITMQ_OMOTES_USER_PASSWORD: "c29tZXBhc3Mx"
  RABBITMQ_CELERY_USER_PASSWORD: "c29tZXBhc3My"

  INFLUXDB_ADMIN_PASSWORD: "OTAxMg=="
  INFLUXDB_WRITE_USER_PASSWORD: "d3JpdGU5MDEy"
  INFLUXDB_FRONTEND_ADMIN_USER_PASSWORD: "ZnJvbnQ5MDEy"
