apiVersion: v1
kind: Service
metadata:
  namespace: omotes
  labels:
    app: influxdb
  name: omotes-influxdb
spec:
  ports:
    - name: "8096"
      port: 8096
      targetPort: 8096
    - name: "8098"
      port: 8098
      targetPort: 8098
  selector:
    app: influxdb
