apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: omotes
  labels:
    app: mesido-worker-optimizer
  name: mesido-worker-optimizer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mesido-worker-optimizer
  template:
    metadata:
      labels:
        app: mesido-worker-optimizer
    spec:
      containers:
        - env:
            - name: INFLUXDB_HOSTNAME
              value: omotes-influxdb
            - name: INFLUXDB_PORT
              valueFrom:
                configMapKeyRef:
                  name: env-vars-cm
                  key: INFLUXDB_PORT
            - name: INFLUXDB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: env-vars-cm
                  key: INFLUXDB_FRONTEND_ADMIN_USER
            - name: INFLUXDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: env-vars-secrets
                  key: INFLUXDB_FRONTEND_ADMIN_USER_PASSWORD
            - name: RABBITMQ_HOSTNAME
              value: omotes-rabbitmq
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: env-vars-cm
                  key: RABBITMQ_CELERY_USER_NAME
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: env-vars-secrets
                  key: RABBITMQ_CELERY_USER_PASSWORD
            - name: RABBITMQ_VIRTUALHOST
              value: omotes_celery
            - name: GROW_TASK_TYPE
              value: grow_optimizer_default
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: env-vars-cm
                  key: LOG_LEVEL
          image: ghcr.io/project-omotes/omotes-grow-optimizer-worker:2.0.1
          name: mesido-worker-optimizer
      restartPolicy: Always
