apiVersion: v1
kind: ConfigMap
metadata:
  namespace: omotes
  annotations:
    use-subpath: "true"
  labels:
    app: orchestrator
  name: orchestrator-workflows-cm
data:
  workflow_config_nwn.json: |-
    [
      {
        "workflow_type_name": "grow_optimizer_no_heat_losses",
        "workflow_type_description_name": "Draft Design - Quickscan Validation"
      },
      {
        "workflow_type_name": "grow_optimizer_default",
        "workflow_type_description_name": "Draft Design - Optimization"
      },
      {
        "workflow_type_name": "grow_optimizer_with_pressure",
        "workflow_type_description_name": "Draft Design - Optimization with Pressure Drops"
      },
      {
        "workflow_type_name": "grow_simulator",
        "workflow_type_description_name": "Draft Design - Simulation with Source Merit Order"
      },
      {
        "workflow_type_name": "simulator",
        "workflow_type_description_name": "Conceptual Design - Simulation"
      },
      {
        "workflow_type_name": "test_worker",
        "workflow_type_description_name": "Used for testing purposes. Should not be used in production environments.",
        "workflow_parameters": [
          {
            "parameter_type": "datetime",
            "key_name": "start_time"
          },
          {
            "parameter_type": "datetime",
            "key_name": "end_time"
          },
          {
            "parameter_type": "integer",
            "key_name": "step_size_in_minutes",
            "title": "This will override the 'capitalized, underscore to space', key_name",
            "description": "Description/explanation.",
            "default": 900,
            "minimum": 1,
            "maximum": 525600
          },
          {
            "parameter_type": "integer",
            "key_name": "number_of_steps",
            "minimum": 1
          },
          {
            "parameter_type": "string",
            "key_name": "test_enum",
            "description": "How to use enum options",
            "enum_options": [
              {
                "key_name": "key1",
                "display_name": "Display name 1"
              },
              {
                "key_name": "key2",
                "display_name": "Display name 2"
              }
            ]
          }
        ]
      }
    ]
