apiVersion: v1
kind: ConfigMap
metadata:
  namespace: omotes
  annotations:
    use-subpath: "true"
  name: postgres-init-cm
data:
  init.sql: |
    CREATE USER :POSTGRESQL_USERNAME WITH PASSWORD :'POSTGRESQL_PASSWORD';
    ALTER USER :POSTGRESQL_USERNAME WITH PASSWORD :'POSTGRESQL_PASSWORD';
    GRANT ALL PRIVILEGES ON DATABASE omotes_jobs TO :POSTGRESQL_USERNAME;
    GRANT ALL PRIVILEGES ON SCHEMA public TO :POSTGRESQL_USERNAME;
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO :POSTGRESQL_USERNAME;
    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO :POSTGRESQL_USERNAME;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO :POSTGRESQL_USERNAME;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO :POSTGRESQL_USERNAME;
